### ISSUE TITLE
not compatible with Cast?

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-toggle-lock-entity-row#16]
loading this:

```
  - type: entities
    title: Tradfri automations & scripts
    show_header_toggle: true
    entities:
      - entity: automation.tradfri_parking_light_shows_unavailable
        secondary_info: last-triggered
      - type: custom:toggle-lock-entity-row
        entity: script.reset_ikea_hub
        secondary_info: last-triggered
      - type: custom:toggle-lock-entity-row
        entity: switch.sw_everspring_no_template
        secondary_info: last-changed
```

on a type:cast card results in:

```
Custom element doesn't exist
```

for the 2 bottom entities in the card.
please check if toggle-lock-entity-row has issues with Cast?
