### ISSUE TITLE
Support for entity-button type

### ISSUE THREAD

**Issue by elRadix** [thomasloven/lovelace-toggle-lock-entity-row#5]
as the title says

**Comment by iantrich** [comment]
@thomasloven what do you think about adding a toggle-lock-card to core that is like the unavailable overlay in the light card?
![image](https://user-images.githubusercontent.com/1287159/66656711-22d63a00-ec04-11e9-8816-f1d683c7ddd9.png)
Instead of the "Unavailable" text, we put the lock icon on the top right and when you click on it the lock is remove for x seconds and you can interact with the card
e.g.
```yaml
type: toggle-lock
delay: 5
card:
  type: thermostat
  entity: climate.house
```
could have a row and element as well.
