### ISSUE TITLE
Several custom cards at once

### ISSUE THREAD

**Issue by advokatb** [thomasloven/lovelace-toggle-lock-entity-row#6]
Hi.

I'm trying to implement this card to my smart plug but I already have `secondaryinfo-entity-row` there.

```
      - card:
          entities:         
              - entity: switch.xiaomi_smart_plug
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "[[ switch.xiaomi_smart_plug.attributes.load_power ]] W / [[ switch.xiaomi_smart_plug.attributes.power_consumed ]] W" 
                name: Plug №1
          show_header_toggle: false
          theme: dark2
          title: ЗАЛ
          type: entities
        style:
          background-blend-mode: multiply
          background-color: 'rgba(180,180,180,0.5)'
          background-image: url("/local/images/grey_theme/office.png")
          background-position: 130% -2%
          background-repeat: no-repeat
          border-radius: 10px
          font-weight: 600
          color: 'rgba(100,100,100,1)'
          box-shadow: >-
            -5px 5px 13px -7px #999999, 5px 5px 13px -7px #999999, 0px 2px
            0px 0px rgba(90,90,90,0.5), 0px 0px 1px 1px rgba(0,0,0,0.1)
        type: 'custom:card-modder'
```

I want to block entity: switch.xiaomi_smart_plug but also want to show consumed power. 
Is it possible?
Thanks.
